/// <reference lib="webworker" />
/**
 * SQLite runs in a worker so that OPFS access never blocks the UI thread.
 *
 * OPFS gives us a real file-backed database that survives reloads. It needs the
 * page to be cross-origin isolated (COOP/COEP) — see vite.config.ts. When that
 * is missing, or the browser has no OPFS, we fall back to an in-memory database
 * so the app still runs; the client surfaces which mode is active, because a
 * memory database silently losing everything on reload would be the worst
 * possible failure mode for a health log.
 */

import sqlite3InitModule from '@sqlite.org/sqlite-wasm';
import { MIGRATIONS } from './migrations';

type Req =
  | { id: number; type: 'init' }
  | { id: number; type: 'exec'; sql: string; bind?: unknown[] }
  | { id: number; type: 'export' };

type Ok = { id: number; ok: true; result: unknown };
type Err = { id: number; ok: false; error: string };

// The sqlite-wasm typings are loose around the oo1 namespace; these local
// shapes cover exactly what we use.
type OoDb = {
  exec(opts: {
    sql: string;
    bind?: unknown[];
    rowMode?: string;
    returnValue?: string;
  }): unknown;
  selectValue(sql: string): unknown;
  close(): void;
  pointer: number;
};

type Capi = { sqlite3_js_db_export(ptr: number): Uint8Array };

let db: OoDb | null = null;
let capi: Capi | null = null;
let mode: 'opfs' | 'memory' = 'memory';

async function init(): Promise<{ mode: string; version: number }> {
  if (db) return { mode, version: currentVersion() };

  const sqlite3 = await sqlite3InitModule();

  const oo1 = (sqlite3 as unknown as { oo1: Record<string, unknown> }).oo1;
  capi = (sqlite3 as unknown as { capi: Capi }).capi;

  if ('OpfsDb' in oo1 && typeof oo1.OpfsDb === 'function') {
    const Ctor = oo1.OpfsDb as new (path: string) => OoDb;
    db = new Ctor('/mealo.sqlite3');
    mode = 'opfs';
  } else {
    const Ctor = oo1.DB as new (path: string, flags: string) => OoDb;
    db = new Ctor(':memory:', 'ct');
    mode = 'memory';
  }

  db.exec({ sql: 'PRAGMA foreign_keys = ON;' });
  migrate();
  return { mode, version: currentVersion() };
}

function currentVersion(): number {
  if (!db) return 0;
  return Number(db.selectValue('PRAGMA user_version') ?? 0);
}

function migrate(): void {
  if (!db) throw new Error('database not open');
  const from = currentVersion();
  for (const m of MIGRATIONS) {
    if (m.version <= from) continue;
    db.exec({ sql: 'BEGIN' });
    try {
      db.exec({ sql: m.sql });
      // PRAGMA cannot be parameterised; version is a literal from our own code.
      db.exec({ sql: `PRAGMA user_version = ${m.version}` });
      db.exec({ sql: 'COMMIT' });
      console.info(`[db] migrated to v${m.version} — ${m.name}`);
    } catch (e) {
      db.exec({ sql: 'ROLLBACK' });
      throw e;
    }
  }
}

function exec(sql: string, bind?: unknown[]): unknown[] {
  if (!db) throw new Error('database not open');
  return db.exec({
    sql,
    bind,
    rowMode: 'object',
    returnValue: 'resultRows',
  }) as unknown[];
}

/**
 * Serialise the whole database to a byte array — this is the plain, unencrypted
 * export that Phase 1 ships as a "download my data" button. Encryption and a
 * separate export password come in Phase 5; the point of having it this early
 * is that from Phase 1 onward there is real logged data that cannot be
 * regenerated by writing more code.
 */
function exportDb(): Uint8Array {
  if (!db || !capi) throw new Error('database not open');
  if (typeof capi.sqlite3_js_db_export !== 'function') {
    throw new Error('this sqlite-wasm build has no sqlite3_js_db_export');
  }
  return capi.sqlite3_js_db_export(db.pointer);
}

self.onmessage = async (ev: MessageEvent<Req>) => {
  const req = ev.data;
  const reply = (msg: Ok | Err) => (self as DedicatedWorkerGlobalScope).postMessage(msg);
  try {
    switch (req.type) {
      case 'init':
        reply({ id: req.id, ok: true, result: await init() });
        break;
      case 'exec':
        reply({ id: req.id, ok: true, result: exec(req.sql, req.bind) });
        break;
      case 'export':
        reply({ id: req.id, ok: true, result: exportDb() });
        break;
    }
  } catch (e) {
    reply({
      id: req.id,
      ok: false,
      error: e instanceof Error ? `${e.message}` : String(e),
    });
  }
};
